# .github/workflows/jitpack-prebuild.yml
name: Trigger JitPack Build

on:
  push:
    tags:
      - 'v*'

jobs:
  jitpack-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger JitPack build
        run: |
          curl -s -X POST "https://jitpack.io/api/builds" \
            -H "Content-Type: application/json" \
            -d '{"repo":"github.com/${{ github.repository }}","tag":"${GITHUB_REF_NAME}"}'
